---
- hosts: ansible
  become: yes

  tasks:
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ensure webapp_content directory exists
      file:
        path: /opt/Docker/webapp_content
        state: directory

    - name: Copy WAR file to webapp_content
      fetch:
        src: /var/lib/jenkins/workspace/LoginWebApp_CI_Job/target/LoginWebApp.war
        dest: /opt/Docker/webapp_content/LoginWebApp.war
        flat: yes
      delegate_to: jenkins-server

    - name: Build Docker image
      command: docker build -t loginwebapp:latest .
      args:
        chdir: /opt/Docker

    - name: Tag Docker image
      command: docker tag loginwebapp:latest edisongomezs/loginwebapp:latest

    - name: Push Docker image
      command: docker push edisongomezs/loginwebapp:latest

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /opt/Docker
