version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty@12345
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  web:
    image: edisongomezs/loginwebapp:latest
    depends_on:
      - db
    ports:
      - "8080:8080"