version: '3.1'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty@12345
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  web:
    image: edisongomezs/loginwebapp:latest
    container_name: loginwebapp-container
    depends_on:
      - db
    ports:
      - "8080:8080"
