version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: PASS12345
      MYSQL_DATABASE: USUARIOS
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d 

  web:
    build: .
    image: edisongomezs/loginwebapp:latest
    ports:
      - "8080:8080"
    depends_on:
      - db