services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Qwerty@12345
      MYSQL_DATABASE: sample
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d    
    networks:
      - mynetwork

  web:
    build: .
    image: login-webapp
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
