---
- hosts: kubernetes
  become: yes

  tasks:
    - name: Apply MySQL InitDB ConfigMap
      command: kubectl apply -f /opt/Docker/mysql-initdb-config.yml

    - name: Apply MySQL Persistent Volume
      command: kubectl apply -f /opt/Docker/mysql-pv.yml

    - name: Apply MySQL Persistent Volume Claim
      command: kubectl apply -f /opt/Docker/mysql-pv-claim.yml

    - name: Deploy MySQL on Kubernetes
      command: kubectl apply -f /opt/Docker/mysql-deployment.yml

    - name: Create service for MySQL
      command: kubectl apply -f /opt/Docker/mysql-service.yml

    - name: Deploy loginwebapp on Kubernetes
      command: kubectl apply -f /opt/Docker/loginwebapp-deployment.yml

    - name: Create service for loginwebapp
      command: kubectl apply -f /opt/Docker/loginwebapp-service.yml

    - name: Update deployment with new pods if image updated in Docker Hub
      command: kubectl rollout restart deployment.apps/loginwebapp
