---
- hosts: kubernetes
  user: root

  tasks:
    - name: deploy loginwebapp on kubernetes
      command: kubectl apply -f /opt/Docker/loginwebapp-deployment.yml

    - name: create service for loginwebapp
      command: kubectl apply -f /opt/Docker/loginwebapp-service.yml

    - name: update deployment with new pods if image updated in docker hub
      command: kubectl rollout restart deployment.apps/loginwebapp
