---
- hosts: kubernetes
  become: yes

  tasks:
    - name: Copy Deployment file from Jenkins to Ansible server
      fetch:
        src: /var/lib/jenkins/workspace/LoginWebApp_CI_Job/loginwebapp-deployment.yml
        dest: /opt/Docker/loginwebapp-deployment.yml
        flat: yes
      delegate_to: jenkins-server

    - name: Copy Service file from Jenkins to Ansible server
      fetch:
        src: /var/lib/jenkins/workspace/LoginWebApp_CI_Job/loginwebapp-service.yml
        dest: /opt/Docker/loginwebapp-service.yml
        flat: yes
      delegate_to: jenkins-server

    - name: Deploy loginwebapp on Kubernetes
      command: kubectl apply -f /opt/Docker/loginwebapp-deployment.yml

    - name: Create service for loginwebapp
      command: kubectl apply -f /opt/Docker/loginwebapp-service.yml

    - name: Update deployment with new pods if image updated in Docker Hub
      command: kubectl rollout restart deployment.apps/loginwebapp
