---
- hosts: kubernetes
  become: yes

  tasks:
    - name: Verificar si el archivo mysql-initdb-config.yml existe en Ansible
      stat:
        path: /opt/Docker/mysql-initdb-config.yml
      register: mysql_initdb_config

    - name: Copiar archivos a Kubernetes
      copy:
        src: /opt/Docker/
        dest: /opt/Docker/
      when: mysql_initdb_config.stat.exists

    - name: Aplicar MySQL InitDB ConfigMap
      command: kubectl apply -f /opt/Docker/mysql-initdb-config.yml
      when: mysql_initdb_config.stat.exists

    - name: Aplicar MySQL Persistent Volume
      command: kubectl apply -f /opt/Docker/mysql-pv.yml

    - name: Aplicar MySQL Persistent Volume Claim
      command: kubectl apply -f /opt/Docker/mysql-pv-claim.yml

    - name: Desplegar MySQL en Kubernetes
      command: kubectl apply -f /opt/Docker/mysql-deployment.yml

    - name: Crear servicio para MySQL
      command: kubectl apply -f /opt/Docker/mysql-service.yml

    - name: Desplegar loginwebapp en Kubernetes
      command: kubectl apply -f /opt/Docker/loginwebapp-deployment.yml

    - name: Crear servicio para loginwebapp
      command: kubectl apply -f /opt/Docker/loginwebapp-service.yml

    - name: Actualizar el despliegue con nuevos pods si la imagen se actualizó en Docker Hub
      command: kubectl rollout restart deployment.apps/loginwebapp

- hosts: elastic
  become: yes

  tasks:
    - name: Copiar archivo elasticsearch.yml al servidor Elastic
      copy:
        src: /opt/Docker/elasticsearch.yml
        dest: /etc/elasticsearch/elasticsearch.yml

    - name: Copiar archivo logstash-mysql.conf al servidor Elastic
      copy:
        src: /opt/Docker/logstash-mysql.conf
        dest: /etc/logstash/conf.d/logstash-mysql.conf

    - name: Reiniciar servicio Elasticsearch
      service:
        name: elasticsearch
        state: restarted

    - name: Reiniciar servicio Logstash
      service:
        name: logstash
        state: restarted

- hosts: ansible
  become: yes

  tasks:
    - name: Ejecutar script de despliegue Docker
      command: /opt/Docker/deploy_docker.sh

- hosts: jenkins
  become: yes

  tasks:
    - name: Copiar script Pingdom Monitor al servidor Jenkins
      copy:
        src:  /opt/jenkins/pingdom_create_monitor.sh
        dest: /var/lib/jenkins/workspace/Pingdom_Monitor/pingdom_create_monitor.sh
        mode: '0755'

    - name: Ejecutar script Pingdom Monitor en el servidor Jenkins
      command: /var/lib/jenkins/workspace/Pingdom_Monitor/pingdom_create_monitor.sh
