apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginwebapp-deployment
  labels:
     app: loginwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginwebapp
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
      - name: loginwebapp
        image: edisongomezs/loginwebapp:latest
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
