apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginwebapp
  labels:
    app: loginwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginwebapp
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
      - name: loginwebapp
        image: edisongomezs/loginwebapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
