apiVersion: v1
kind: Service
metadata:
  name: loginwebapp-service
  labels:
    app: loginwebapp
spec:
  selector:
    app: loginwebapp
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
