apiVersion: apps/v1
kind: Deployment
metadata:
  name: loginwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loginwebapp
  template:
    metadata:
      labels:
        app: loginwebapp
    spec:
      containers:
      - name: loginwebapp
        image: edisongomezs/loginwebapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_HOST
          value: "mysql"
        - name: DATABASE_USER
          value: "root"
        - name: DATABASE_PASSWORD
          value: "Qwerty@12345"
        - name: DATABASE_NAME
          value: "sample"
